<a href="https://colab.research.google.com/github/Sanj33d/Array/blob/main/220_Lab1_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# T1 done
import numpy as np

sequence = np.array([10,20,30,40,50,60])
beats = np.array([1,0,0,1,0,1])

def playRight(seq, bts):

  i = 0
  while i<len(bts):
    if bts[i] == 1:

      temp = seq[len(seq)-1]
      j = len(seq)-1
      while j>0:
        seq[j] = seq[j-1]
        j -= 1
      seq[0] = temp
    i += 1
  return seq
print(playRight(sequence,beats))

[40 50 60 10 20 30]


In [ ]:
# T2 done
import numpy as np

cards = np.array([10,2,30,2,50,2,2,0,0])

def discardCards(crd, num):

  size = 0

  x = 0
  while x<len(crd):
    if crd[x] != 0 and crd[x] != None:
      size += 1
    x += 1

  y = 0
  while y<size:
    if crd[y] == num:
      z = y
      while z<size-1:  ## z<size dile out of range hoye jay
        crd[z] = crd[z+1]
        z += 1
      crd[size-1] = 0
      size -= 1
    y += 1

  if crd[size-1] == num:
      crd[size-1] = 0
      size -= 1 # dorkar nai, but imp for projects

                      # just for a wrong indentation,
  return crd           ## it took me 50 mins to debug
print(discardCards(cards,2))

[10 30 50  0  0  0  0  0  0]


In [ ]:
# T3 done
import numpy as np

pokemon_1 = np.array([12, 3, 25, 1, None])
pokemon_2 = np.array([5, -9, 3, None, None])

def mergeLineup(pok1, pok2):

  res = np.array([None]*len(pok1))

  x = 0
  y = len(pok2)-1
  while x<len(pok1):
    if pok1[x] == None:
      pok1[x] = 0
    if pok2[y] == None:
      pok2[y] = 0
    res[x] = pok1[x] + pok2[y]
    x += 1
    y -= 1

  return res
print(mergeLineup(pokemon_1, pokemon_2))

[12 3 28 -8 5]


In [ ]:
# T4 done
import numpy as np

salami = np.array([10, 3, 1, 2, 10])

def balanceSalami(sal):

  toggle = True
  sumx = 0
  sumy = 0

  x = 0
  y = len(sal)-1
  while x<len(sal)//2:  ### most important

    sumx += sal[x]
    sumy += sal[y]

    x += 1
    y -= 1

  if sumx == sumy:
    toggle = False #cuz mid element karo shathe add hoilei unequal hoye jabe

  elif sumx<sumy:
    sumx += sal[len(sal)//2]
    if sumx == sumy:
      toggle = True
    else:
      toggle = False

  else:
    sumy += sal[len(sal)//2]
    if sumx == sumy:
      toggle = True
    else:
      toggle = False

  return toggle

print(balanceSalami(salami))

True


In [ ]:
# T5 without using in and not in

import numpy as np

salami = salami = np.array([4,5,6,6,4,3,6,4])

def protectSalami(sal):

  mt_arr = np.array([1]*len(sal))

  x = 0
  while x<len(sal):

    y = x + 1
    while y<len(sal):
      if sal[x] == sal[y]:
        mt_arr[x] += 1
      y += 1

    x += 1

  z = 0
  largest = mt_arr[0]
  while z<len(mt_arr):
    if mt_arr[z]>largest:
      largest = mt_arr[z]
    z += 1

  counter = 0
  if largest>1:  # if the largest element of the new array is more than 1
    p = 0
    counter = 0
    while p<len(mt_arr):
      if mt_arr[p] == largest:
        counter += 1
      p += 1


  if counter>1:
    return True   ## if the largest element comes atleast 2 times, then True
  else:
    return False

print(protectSalami(salami))

True


In [ ]:
# Part2 done

import numpy as np

my_arr = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])

def meancalculator(arr):

  sum = 0
  i = 0
  while i<len(arr):
    sum += my_arr[i]
    i += 1

  mean = sum/len(arr)

  return mean
print('The mean of the numbers is:',meancalculator(my_arr))
#######################

my_arr = np.array([10, 8, 13, 9, 14, 25, -5, 20, 7, 7, 4])

def std_dev_calculator(arr):

  mean = meancalculator(arr)

  j = 0
  sum = 0
  while j<len(arr):
    sum += (arr[j]-mean)**2
    j += 1

  std_dev = (sum/len(arr))**(1/2)
  return std_dev
print('The standard deviation is:',std_dev_calculator(my_arr))
##################################
def newarray_calculator(arr):

  upper_val = meancalculator(arr) + 1.5*std_dev_calculator(arr)
  lower_val = meancalculator(arr) - 1.5*std_dev_calculator(arr)

  counter = 0
  k = 0
  while k<len(arr):
    if arr[k]<=lower_val or arr[k]>=upper_val:
      counter += 1
    k += 1

  newarr = np.array([None]*counter)

  x = 0
  y = 0
  while x<len(arr):
    if arr[x]<=lower_val or arr[x]>=upper_val:
      newarr[y] = arr[x]
      y += 1
    x += 1

  return newarr
print('New array',newarray_calculator(my_arr))